### ISSUE TITLE
docs in English as well please?

### ISSUE THREAD

**Issue by NirantK** [wabyking/TextClassificationBenchmark#16]
Hello, 

Can I raise a PR with [docs](https://github.com/wabyking/TextClassificationBenchmark/blob/master/docs/) in English? 

This would help your work reach a larger audience.

**Comment by wabyking** [comment]
Thank you. Please do it.

**Comment by NirantK** [comment]
Hello @wabyking, I've raised a new PR with the translated docs files.

**Comment by NirantK** [comment]
Closing this issue, thanks for the invite to collaborate and push access @wabyking!
