### ISSUE TITLE
Does it need a new Data preprocess to raplace torchText?

### ISSUE THREAD

**Issue by wabyking** [wabyking/TextClassificationBenchmark#2]

**Comment by surmountwei** [comment]
Yes. Actually it's impossible for torchtext to support all the datasets we may use, to build a new data process script is necessary. At first, maybe we only need to write the script for these datasets which can not be processed by torchtext.

**Comment by wabyking** [comment]
New  Data preprocess has been implemented~ 
A new dataset only need a simple adapter.
